{% set name = "hatch-vcs" %}
{% set version = "0.4.0" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatch_vcs-{{ version }}.tar.gz
  sha256: 093810748fe01db0d451fabcf2c1ac2688caefd232d4ede967090b1c1b07d9f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - hatchling >=1.1.0
    - pip
    - python {{ python_min }}
  run:
    - hatchling >=1.1.0
    - python >={{ python_min }}
    - setuptools-scm >=6.4.0

test:
  imports:
    - hatch_vcs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/hatch-vcs/
  summary: Hatch plugin for versioning with your preferred VCS
  dev_url: https://github.com/ofek/hatch-vcs
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nicoddemus
